language: python
sudo: false
python:
- '2.7'

install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- |
  conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy=1.11 ipython-notebook pandas pytest matplotlib scikit-learn pyyaml
- source activate test-environment
- conda list
- pip install pandana geopy osmnet
- pip install .

script:
- py.test
- cd demo; jupyter nbconvert --to python simple_example.ipynb
- cd demo; python simple_example.py
- cd urbanaccess/tests/integration; python integration_madison.py
- cd urbanaccess/tests/integration; python integration_sandiego.py
- cd urbanaccess/tests/integration; python integration_gb.py